version: '3.3'

services:
  moekoe-music:
    # 镜像地址
    image: registry.cn-wulanchabu.aliyuncs.com/youngxj/moekoe-music:latest
    container_name: moekoe-music # 容器名
    restart: unless-stopped # 自动重启
    build:
      context: .
      dockerfile: Dockerfile
    ports: # 端口映射
      - "8080:8080"  # 前端服务
      - "6521:6521"  # 接口服务